# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'

  # Pods for iOSDemoApp

  target 'iOSDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSDemoAppUITests' do
    # Pods for testing
  end

end
